"""Remove default from source column

Revision ID: 52e363be6414
Revises: bce8cccd8bc7
Create Date: 2025-02-24 04:40:32.770224

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "52e363be6414"
down_revision: Union[str, None] = "bce8cccd8bc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documents", "source", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documents", "source", server_default="your_default_value")
    # ### end Alembic commands ###
