"""Added Source to base Document model

Revision ID: bce8cccd8bc7
Revises: bdc6e672738c
Create Date: 2025-02-24 04:37:21.832147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce8cccd8bc7'
down_revision: Union[str, None] = 'bdc6e672738c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(), nullable=False, server_default=None))
    op.add_column('documents', sa.Column('url', sa.String(), nullable=True))
    op.alter_column('documents', 'content',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('documents', 'url')
    op.alter_column('documents', 'source', server_default='unknown')
    # ### end Alembic commands ###
